CREATE TABLE IF NOT EXISTS "quiz-app_quizzes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quiz-app_quizzes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text,
	"unique_id" text,
	"questions" text[],
	"results" text[]
);
